version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    env_file:
      - ./.env
    container_name: worklog_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: ${SERVICE_NAME_APP}
      SERVICE_TAGS: ${SERVICE_TAGS}
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./config-docker/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  web:
    image: nginx:alpine
    container_name: worklog_web
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./config-docker/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7
    env_file:
      - ./.env
    container_name: worklog_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: ${SERVICE_TAGS}
      SERVICE_NAME: ${SERVICE_NAME_DB}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./config-docker/db-init.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./config-docker/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge